// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgE2X5B5IEIon_eyIKZDELK6ikqtj5Tmk',
    appId: '1:421436915348:web:ded941842757410a88be81',
    messagingSenderId: '421436915348',
    projectId: 'nonsensegenerator-d140d',
    authDomain: 'nonsensegenerator-d140d.firebaseapp.com',
    storageBucket: 'nonsensegenerator-d140d.firebasestorage.app',
    measurementId: 'G-KEJJVXVT1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe0-Fqe3l83CdmCRNX1hWtRr0ZqKxcir8',
    appId: '1:421436915348:android:36cacd71d8f0d13988be81',
    messagingSenderId: '421436915348',
    projectId: 'nonsensegenerator-d140d',
    storageBucket: 'nonsensegenerator-d140d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqIKsa55jE1irsa1NNXWhOoOBRZPCzpws',
    appId: '1:421436915348:ios:f13f4db1da06fd0788be81',
    messagingSenderId: '421436915348',
    projectId: 'nonsensegenerator-d140d',
    storageBucket: 'nonsensegenerator-d140d.firebasestorage.app',
    iosBundleId: 'com.unanimousworks.nonsense-generator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqIKsa55jE1irsa1NNXWhOoOBRZPCzpws',
    appId: '1:421436915348:ios:d9fc1cdd65ad510688be81',
    messagingSenderId: '421436915348',
    projectId: 'nonsensegenerator-d140d',
    storageBucket: 'nonsensegenerator-d140d.firebasestorage.app',
    iosBundleId: 'com.example.nonsenseGenerator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgE2X5B5IEIon_eyIKZDELK6ikqtj5Tmk',
    appId: '1:421436915348:web:137b2b208eec3a2588be81',
    messagingSenderId: '421436915348',
    projectId: 'nonsensegenerator-d140d',
    authDomain: 'nonsensegenerator-d140d.firebaseapp.com',
    storageBucket: 'nonsensegenerator-d140d.firebasestorage.app',
    measurementId: 'G-V3NR9RKPJK',
  );

}